In [5]:
import pandas as pd
flight_status = pd.read_csv('/Users/gauravgoel/Documents/workspace/berkeley/python/datasets_starter/archive/flights_sample_3m_small.csv')

In [9]:
flight_status

df = pd.DataFrame(flight_status)
df

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,2020-03-21,SkyWest Airlines Inc.,SkyWest Airlines Inc.: OO,OO,20304,4330,MQT,"Marquette, MI",DTW,"Detroit, MI",...,0.0,88.0,81.0,56.0,349.0,NaN,NaN,NaN,NaN,NaN
495,2019-01-14,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,929,ORD,"Chicago, IL",MCO,"Orlando, FL",...,0.0,164.0,160.0,124.0,1005.0,NaN,NaN,NaN,NaN,NaN
496,2019-06-05,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2054,ATL,"Atlanta, GA",HSV,"Huntsville, AL",...,0.0,55.0,47.0,33.0,151.0,NaN,NaN,NaN,NaN,NaN
497,2023-05-27,American Airlines Inc.,American Airlines Inc.: AA,AA,19805,707,AUS,"Austin, TX",DFW,"Dallas/Fort Worth, TX",...,0.0,73.0,54.0,38.0,190.0,NaN,NaN,NaN,NaN,NaN
498,2021-05-11,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,4707,SNA,"Santa Ana, CA",LAS,"Las Vegas, NV",...,0.0,70.0,62.0,41.0,226.0,NaN,NaN,NaN,NaN,NaN

In [10]:
# Describe numeric columns (default behavior)
print("Descriptive statistics for numeric columns:")
print(df.describe())

# Describe all columns, including categorical
print("\nDescriptive statistics for all columns:")
print(df.describe(include='all'))

Descriptive statistics for numeric columns:
           DOT_CODE    FL_NUMBER  CRS_DEP_TIME     DEP_TIME    DEP_DELAY  \
count    499.000000   499.000000    499.000000   488.000000   488.000000
mean   19960.146293  2399.172345   1320.376754  1321.018443     8.713115
std      375.823707  1714.677327    492.216349   502.452778    56.646565
min    19393.000000     1.000000     59.000000    29.000000   -21.000000
25%    19790.000000   980.500000    853.500000   889.000000    -5.000000
50%    19930.000000  2027.000000   1320.000000  1316.500000    -3.000000
75%    20363.000000  3619.500000   1726.000000  1740.250000     6.000000
max    20452.000000  6524.000000   2359.000000  2357.000000  1069.000000

         TAXI_OUT   WHEELS_OFF    WHEELS_ON     TAXI_IN  CRS_ARR_TIME  ...  \
count  488.000000   488.000000   488.000000  488.000000    499.000000  ...
mean    16.401639  1344.551230  1462.387295    7.750000   1484.739479  ...
std      9.950935   504.691702   540.576557    6.088246    529.099056  ...
min      5.000000     8.000000     2.000000    1.000000      6.000000  ...
25%     11.000000   919.000000  1033.250000    4.000000   1042.500000  ...
50%     14.000000  1326.500000  1501.000000    6.000000   1521.000000  ...
75%     18.000000  1752.000000  1917.250000    9.000000   1922.500000  ...
max    131.000000  2357.000000  2357.000000   47.000000   2359.000000  ...

       DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME    AIR_TIME     DISTANCE  \
count     499.0        499.000000    488.000000  488.000000   499.000000
mean        0.0        141.196393    135.143443  110.991803   796.188377
std         0.0         68.562444     68.890980   67.274453   562.544357
min         0.0         36.000000     32.000000   15.000000    68.000000
25%         0.0         90.000000     83.750000   59.750000   380.000000
50%         0.0        124.000000    117.500000   95.000000   660.000000
75%         0.0        175.000000    166.250000  140.250000  1046.000000
max         0.0        385.000000    383.000000  344.000000  2845.000000

       DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  DELAY_DUE_NAS  \
count          87.000000          87.000000      87.000000
mean           16.574713           5.689655      23.643678
std            29.419434          27.754032     120.787337
min             0.000000           0.000000       0.000000
25%             0.000000           0.000000       0.000000
50%             2.000000           0.000000       0.000000
75%            23.500000           0.000000      18.000000
max           141.000000         232.000000    1124.000000

       DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
count                87.0                87.000000
mean                  0.0                17.390805
std                   0.0                44.804058
min                   0.0                 0.000000
25%                   0.0                 0.000000
50%                   0.0                 0.000000
75%                   0.0                18.500000
max                   0.0               333.000000

[8 rows x 23 columns]

Descriptive statistics for all columns:
           FL_DATE                 AIRLINE                 AIRLINE_DOT  \
count          499                     499                         499
unique         440                      18                          18
top     2022-09-13  Southwest Airlines Co.  Southwest Airlines Co.: WN
freq             3                     100                         100
mean           NaN                     NaN                         NaN
std            NaN                     NaN                         NaN
min            NaN                     NaN                         NaN
25%            NaN                     NaN                         NaN
50%            NaN                     NaN                         NaN
75%            NaN                     NaN                         NaN
max            NaN                     NaN                         NaN

       AIRLINE_CODE      DOT_CODE    FL_NUMBER ORIGIN  ORIGIN_CITY DEST  \
count           499    499.000000   499.000000    499          499  499
unique           18           NaN          NaN    125          120  117
top              WN           NaN          NaN    ATL  Atlanta, GA  ATL
freq            100           NaN          NaN     28           28   27
mean            NaN  19960.146293  2399.172345    NaN          NaN  NaN
std             NaN    375.823707  1714.677327    NaN          NaN  NaN
min             NaN  19393.000000     1.000000    NaN          NaN  NaN
25%             NaN  19790.000000   980.500000    NaN          NaN  NaN
50%             NaN  19930.000000  2027.000000    NaN          NaN  NaN
75%             NaN  20363.000000  3619.500000    NaN          NaN  NaN
max             NaN  20452.000000  6524.000000    NaN          NaN  NaN

          DEST_CITY  ...  DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME  \
count           499  ...     499.0        499.000000    488.000000
unique          113  ...       NaN               NaN           NaN
top     Chicago, IL  ...       NaN               NaN           NaN
freq             27  ...       NaN               NaN           NaN
mean            NaN  ...       0.0        141.196393    135.143443
std             NaN  ...       0.0         68.562444     68.890980
min             NaN  ...       0.0         36.000000     32.000000
25%             NaN  ...       0.0         90.000000     83.750000
50%             NaN  ...       0.0        124.000000    117.500000
75%             NaN  ...       0.0        175.000000    166.250000
max             NaN  ...       0.0        385.000000    383.000000

          AIR_TIME     DISTANCE  DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  \
count   488.000000   499.000000          87.000000          87.000000
unique         NaN          NaN                NaN                NaN
top            NaN          NaN                NaN                NaN
freq           NaN          NaN                NaN                NaN
mean    110.991803   796.188377          16.574713           5.689655
std      67.274453   562.544357          29.419434          27.754032
min      15.000000    68.000000           0.000000           0.000000
25%      59.750000   380.000000           0.000000           0.000000
50%      95.000000   660.000000           2.000000           0.000000
75%     140.250000  1046.000000          23.500000           0.000000
max     344.000000  2845.000000         141.000000         232.000000

        DELAY_DUE_NAS  DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
count       87.000000                87.0                87.000000
unique            NaN                 NaN                      NaN
top               NaN                 NaN                      NaN
freq              NaN                 NaN                      NaN
mean        23.643678                 0.0                17.390805
std        120.787337                 0.0                44.804058
min          0.000000                 0.0                 0.000000
25%          0.000000                 0.0                 0.000000
50%          0.000000                 0.0                 0.000000
75%         18.000000                 0.0                18.500000
max       1124.000000                 0.0               333.000000

[11 rows x 32 columns]